package com.dungeon.logic.grid.builder;

import com.jme3.math.Vector2f;

import java.util.ArrayList;
import java.util.List;

/**
 * Utility for generating a 2D hexagonal point lattice as concentric rings around the origin.
 * <p>
 * The method {@link #generate(int, float)} produces:
 * </p>
 * <ul>
 *   <li>one center vertex at (0,0), and</li>
 *   <li>{@code sideCount} rings around it, where ring {@code r} contains {@code 6*r} vertices.</li>
 * </ul>
 *
 * <p>
 * The coordinate system is based on the axial/cube-hex grid directions projected into 2D.
 * Points are spaced by {@code edgeLength} along the six hex directions, yielding an equilateral
 * triangle grid that can be used as a base for hex-like triangulations.
 * </p>
 */
public final class HexPointGenerator {

    /**
     * Generates a hex-ring point set (center + {@code sideCount} rings).
     * <p>
     * Ring {@code r} (1-based) is generated by:
     * </p>
     * <ol>
     *   <li>Starting at the "east" direction offset {@code r * edgeLength}.</li>
     *   <li>Walking along the six hex sides; each side contributes {@code r} steps, adding one vertex per step.</li>
     * </ol>
     * This results in {@code 6*r} vertices for ring {@code r}.
     *
     * @param sideCount number of rings to generate (must be {@code >= 0})
     * @param edgeLength spacing between neighboring points (must be {@code > 0})
     * @return list of generated vertex positions in the order they were produced
     * @throws IllegalArgumentException if {@code sideCount < 0} or {@code edgeLength <= 0}
     */
    public static List<Vector2f> generate(int sideCount, float edgeLength) {
        if (sideCount < 0) {
            throw new IllegalArgumentException("sideCount must be >= 0");
        }
        if (edgeLength <= 0f) {
            throw new IllegalArgumentException("edgeLength must be > 0");
        }

        List<Vector2f> vertices = new ArrayList<>();

        // 1) Center point
        vertices.add(new Vector2f(0f, 0f));

        // 2) Unit direction vectors for a regular hex grid (scaled later by edgeLength).
        // These correspond to 60° increments on an equilateral triangle grid.
        final float sqrt3Over2 = (float) (Math.sqrt(3.0) * 0.5);
        Vector2f[] directions = new Vector2f[] {
                new Vector2f(-0.5f,  sqrt3Over2),
                new Vector2f(-1f,    0f),
                new Vector2f(-0.5f, -sqrt3Over2),
                new Vector2f( 0.5f, -sqrt3Over2),
                new Vector2f( 1f,    0f),
                new Vector2f( 0.5f,  sqrt3Over2)
        };

        // 3) Concentric rings
        for (int r = 1; r <= sideCount; r++) {
            // Start at "east" (direction index 4) for a stable, simple ring traversal.
            Vector2f pos = directions[4].mult(r * edgeLength);

            // Walk the six sides; each side has exactly r steps.
            for (int side = 0; side < 6; side++) {
                Vector2f stepDir = directions[side].mult(edgeLength);
                for (int step = 0; step < r; step++) {
                    vertices.add(new Vector2f(pos.x, pos.y));
                    pos = pos.add(stepDir);
                }
            }
        }

        return vertices;
    }
}